<a href="https://colab.research.google.com/github/UngJiShin/2025hufs_2/blob/main/matrix_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import the NumPy library, which is essential for numerical operations, especially with arrays and matrices.
# We use the alias 'np' as a standard convention to make the code shorter and more readable.
import numpy as np

# 1. Create a Matrix
# We define a 2x3 matrix (2 rows, 3 columns) using a list of lists.
# The np.array() function converts this list of lists into a NumPy array.
original_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 2. Transpose the Matrix
# NumPy makes transposing a matrix very simple. You can access the .T attribute of any
# NumPy array to get its transpose. The rows become columns and the columns become rows.
transposed_matrix = original_matrix.T

# An alternative method is to use the np.transpose() function, which does the same thing:
# transposed_matrix_alt = np.transpose(original_matrix)

# 3. Print the Results
# Display the original and transposed matrices to see the result of the operation.
print("Original Matrix (A):")
print(original_matrix)
print("\nShape of Original Matrix:", original_matrix.shape) # .shape returns a tuple (rows, columns)

print("\n--------------------------\n")

print("Transposed Matrix (A.T):")
print(transposed_matrix)
print("\nShape of Transposed Matrix:", transposed_matrix.shape)


Original Matrix (A):
[[1 2 3]
 [4 5 6]]

Shape of Original Matrix: (2, 3)

--------------------------

Transposed Matrix (A.T):
[[1 4]
 [2 5]
 [3 6]]

Shape of Transposed Matrix: (3, 2)
